### ISSUE TITLE
Article link doesn't work

### ISSUE THREAD

**Issue by nandorojo** [DNature/expo-yarn-workspace-demo#1]
Hi, the article link in your readme doesn't point anywhere. Is there a post on medium?

**Comment by DNature** [comment]
Hi @nandorojo. I've updated the link. However, you can still check it out here [https://divinehycenth.com/blog/2020-01-02_yarn-workspace-monorepo](https://divinehycenth.com/blog/2020-01-02_yarn-workspace-monorepo)

**Comment by oleksii-lukin** [comment]
Latest link is https://divinehycenth.com/blog/yarn-workspace-monorepo

**Comment by DNature** [comment]
> https://divinehycenth.com/blog/yarn-workspace-monorepo

Hi @llamerr , Thanks for pointing that out. I've replaced the old link on  the README.md with the latest one
